taskpjt/taskapp/urls.py
from django.urls import path
from . import views

app_name = 'taskapp'

urlpatterns = [
    path('', views.home, name="home"),
    path('taskapp/login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('<slug:c_slug>/', views.allBranch, name='branch_by_category'),
    path('register/forms', views.formfill, name='formfill'),
    path('<slug:c_slug>/<slug:sub_slug>/', views.subbranch, name='sub'),
    path('register/taskapp/login', views.login, name='login'),
    path('register/forms/print', views.printform, name='printform'),
]

taskpjt/taskpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("taskapp.urls")),
]

taskpjt/taskapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Branch(models.Model):
    branch_name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ('branch_name',)
        verbose_name = 'branch'
        verbose_name_plural = 'branches'

    def get_url(self):
        return reverse('taskapp:branch_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.branch_name)


class Sub_Branch(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'subbranch'
        verbose_name_plural = 'subbranches'

    def get_url(self):
        return reverse('taskapp:sub', args=[self.branch.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

taskpjt/taskapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

from .models import Branch, Sub_Branch


# Create your views here.
def home(request):
    return render(request, 'home.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, "INVALID CREDENTIALS")
            return redirect('login')

    return render(request, "login.html")


def register(request):
    # b = Background.objects.all()
    if request.method == 'POST':
        u = request.POST['username']
        p = request.POST['password']
        cp = request.POST['cpassword']

        if p == cp:
            if User.objects.filter(username=u).exists():
                messages.info(request, "Username already exists")
                return redirect('register')
            else:
                user = User.objects.create_user(username=u, password=p)
                user.save()
                return redirect('taskapp/login')
        else:
            messages.info("PASSWORD NOT MATCHING")
            return redirect('register')

    return render(request, "register.html")


def logout(request):
    auth.logout(request)
    return redirect('/')


def allBranch(request, c_slug=None):
    c_page = None
    products_list = None
    # products = None
    if c_slug != None:
        c_page = get_object_or_404(Branch, slug=c_slug)
        branch = Branch.objects.all().filter(bch=c_page, available=True)
    else:
        branch = Branch.objects.all().filter(available=True)

    return render(request, 'branch.html', {'bch': c_page})


def formfill(request):
    return render(request, 'form.html')


def subbranch(request, c_slug, sub_slug):
    try:
        s = Sub_Branch.objects.get(branch__slug=c_slug, slug=sub_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'s': s})


def printform(request):
    print(request.POST)
    return render(request, "form.html")

taskpjt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color: #1d2951;">
{% include 'navbar.html' %}
<br>
<img src="{% static 'bg1.jpg' %}" alt="My image" align="center"; width="1200px"; height="500px";>
{% block content %}
{% endblock %}
</body>
</html>

taskpjt/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color: #1d2951; text-align:center;">
{% block content %}
{% endblock %}
</body>
</html>

taskpjt/templates/branch.html
{% extends 'base1.html' %}
{% load static %}
{% block metadescription %}
    {{br.description|truncatewords:155 }}
{% endblock %}
{% block title %}
  {{br.branch_name}}-X-Bank
{% endblock %}
{% block content %}
{% if category %}
{% for branch in branches.object_list %}
<div class="container">

    <div>
        <div>
            <h1>{{branch.branch_name}}</h1>
            <br>
            <p>Description:</p>
            <p>
                {{branch.description}}
            </p>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

taskpjt/templates/form.html
{% extends 'base1.html' %}
{% block content %}

<h1 style="font-family:Perpetua; text-align:center; color: #ffebcd">FILL THE FORM</h1><br><br>

<form action="forms/print" method="post">
    {% csrf_token %}

    <label class="u" style="color: #ffebcd"><h4><b>Name</b></h4></label>
    <input type="text" name="name"><br>
    <label class="u" style="color: #ffebcd"><h4><b>Date of Birth</b></h4></label>
    <input type="date" name="dob"><br>
    <label class="u" style="color: #ffebcd"><h4><b>Age</b></h4></label>
    <input type="number" name="age"><br>
  <div>
    <label class="u" style="color: #ffebcd"><h4><b>Gender</b></h4></label>&nbsp;&nbsp;
    <label class="u" style="color: #ffebcd"><h5><b>Male</b></h5></label>
    <input type="radio" name="gender">
    <label class="u" style="color: #ffebcd"><h5><b>Female</b></h5></label>
    <input type="radio" name="gender">
  </div>
    <label class="u" style="color: #ffebcd"><h4><b>Phone number</b></h4></label>
    <input type="text" name="number"><br>
    <label class="u" style="color: #ffebcd"><h4><b>Email id</b></h4></label>
    <input type="email" name="mail"><br>
    <label class="u" style="color: #ffebcd"><h4><b>Branch</b></h4></label>
    <select name="branch" class="form-control" id="branch">
        <option value="0" label="Select District" selected="selected">Select Branch</option>
        <optgroup id="district-optgroup-TRIVANDRUM" label="TRIVANDRUM">
            <option value="PG" label="PMG">PMG</option>
            <option value="EF" label="PMG">East Fort</option>
            </optgroup>
        <optgroup id="district-optgroup-ERNAKULAM" label="ERNAKULAM">
            <option value="EP" label="Edappally">Edappally</option>
            <option value="AL" label="Aluva">Aluva</option>
            </optgroup>
        <optgroup id="district-optgroup-PALAKKADU" label="PALAKKADU">
            <option value="OP" label="Ottapalam">Ottapalam</option>
            </optgroup>
        <optgroup id="district-optgroup-KOLLAM" label="KOLLAM">
            <option value="KK" label="Kottarakara">Kottarakara</option>
             </optgroup>
        <optgroup id="district-optgroup-TRISSUR" label="TRISSUR">
            <option value="CK" label="Chalakkudy">Chalakkudy</option>
            </optgroup>
    </select><br>
  <div>
    <label class="u" style="color: #ffebcd"><h4><b>Account type:</b></h4></label><br>
    <label class="u" style="color: #ffebcd"><h5><b>Savings</b></h5></label>
    <input type="radio" name="acctype"><br>
    <label class="u" style="color: #ffebcd"><h5><b>Current</b></h5></label>
    <input type="radio" name="acctype"><br>
  </div>
  <div>
    <label class="u" style="color: #ffebcd"><h4><b>Materials provided:</b></h4></label><br>
    <label class="u" style="color: #ffebcd"><h5><b>Cheque Book</b></h5></label>
    <input type="checkbox" name="mat"><br>
    <label class="u" style="color: #ffebcd"><h5><b>Debit</b></h5></label>
    <input type="checkbox" name="mat"><br>
    <label class="u" style="color: #ffebcd"><h5><b>Credit</b></h5></label>
    <input type="checkbox" name="mat"><br>
  </div>
    <div class="col-auto">
        <input type="Submit" class="btn btn-primary mb-3" value="SUBMIT">
    </div>
</form>

{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}


{% endblock %}

taskpjt/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

taskpjt/templates/login.html
{% extends 'base1.html' %}
{% block content %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <div class="container-fluid">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" style="font-family: Perpetua; color: #ffebcd;">
        <h3>X-BANK</h3>
      </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <li class="nav-item">
           <a class="nav-link" href="/">HOME</a>
        </li>
        <li class="nav-item">
           <a class="nav-link" href="/register">REGISTRATION</a>
        </li>
       </ul>
  </div>
</div>
</nav>
        <br>
   <h1 style="font-family:Perpetua; text-align:center; color: #ffebcd">LOGIN</h1>
<form action="forms" method="post">
    {% csrf_token %}
    <label class="u" style="color: #ffebcd"><h2> username</h2></label>
    <input type="text" name="username"><br>
    <label class="u" style="color: #ffebcd"><h2>password</h2></label>
    <input type="text" name="password"><br><br>
<!--    <div class="col-auto">-->
<!--        <input type="Submit" class="btn btn-primary mb-3" value="SUBMIT">-->
<!--    </div>-->
    <a class="btn btn-primary mb-3" href="{% url 'taskapp:formfill' %}"><h2>SUBMIT</h2></a>
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
{% endblock %}

taskpjt/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <div class="container-fluid">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" style="font-family: Perpetua; color: #ffebcd;">
        <h3>X-BANK</h3>
      </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      {% if user.is_authenticated %}
        <li class="nav-item">
           <a class="nav-link" href="taskapp/login">LOGIN</a>
        </li>
        <li class="nav-item">
           <a class="nav-link" href="/register">REGISTRATION</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            BRANCH
           </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">TRIVANDRUM</a>
            <a class="dropdown-item" href="#">ERNAKULAM</a>
            <a class="dropdown-item" href="#">PALAKKADU</a>
            <a class="dropdown-item" href="#">KOLLAM</a>
            <a class="dropdown-item" href="#">TRISSUR</a>
        </div>
      </li>
    </ul>
  </div>
</div>
</nav>

taskpjt/templates/printform.html
{% extends 'base1.html' %}
{% block content %}
    if request.method == 'POST':
        name = request.POST['name']
        dob = request.POST['dob']
        age = request.POST['age']
        gender = request.POST['gender']
        number = request.POST['number']
        mail = request.POST['mail']
        branch = request.POST['branch']
        acctype = request.POST['acctype']
        mat = request.POST['mat']
        formprint = {
            "Name": name,
            "Date of Birth": dob,
            "Age": age,
            "Gender": gender,
            "Number": number,
            "Email": mail,
            "Branch": branch,
            "Acc type": acctype,
            "Materials Required": mat
        }
    return render(request, 'printform.html', {'formprint': formprint})
{% endblock %}

taskpjt/templates/register.html
{% extends 'base1.html' %}
{% block content %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <div class="container-fluid">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" style="font-family: Perpetua; color: #ffebcd;">
        <h3>X-BANK</h3>
      </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <li class="nav-item">
           <a class="nav-link" href="/">HOME</a>
        </li>
       </ul>
  </div>
</div>
</nav>
        <br>

<h1 style="font-family:Perpetua; text-align:center; color: #ffebcd">REGISTRATION</h1><br><br>

<form action="" method="post">
    {% csrf_token %}

    <label class="u" style="color: #ffebcd"><h4><b>Username</b></h4></label>
    <input type="text" name="username"><br>
    <label class="u" style="color: #ffebcd"><h4><b>Password</b></h4></label>
    <input type="password" name="password"><br>
    <label class="u" style="color: #ffebcd"><h4><b>Confirm Password</b></h4></label>
    <input type="password" name="cpassword"><br><br>
    <div class="col-auto">
        <input type="Submit" class="btn btn-primary mb-3" value="SUBMIT">
    </div>
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}


{% endblock %}